{{ $tls := fromYaml ( include "stash.gen-certs" . ) }}
{{- if or .Values.apiserver.enableMutatingWebhook .Values.apiserver.enableValidatingWebhook }}
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.admission.stash.appscode.com
  labels:
    {{- include "stash.labels" . | nindent 4 }}
spec:
  group: admission.stash.appscode.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "stash.fullname" . }}
  caBundle: {{ $tls.caBundle }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.admission.stash.appscode.com
  labels:
    {{- include "stash.labels" . | nindent 4 }}
spec:
  group: admission.stash.appscode.com
  version: v1beta1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "stash.fullname" . }}
  caBundle: {{ $tls.caBundle }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.repositories.stash.appscode.com
  labels:
    {{- include "stash.labels" . | nindent 4 }}
spec:
  group: repositories.stash.appscode.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "stash.fullname" . }}
  caBundle: {{ $tls.caBundle }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stash.fullname" . }}-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stash.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  tls.crt: {{ $tls.tlsCrt }}
  tls.key: {{ $tls.tlsKey }}
---
{{ $promNamespace:= default .Release.Namespace .Values.monitoring.prometheus.namespace }}
{{- if (and (ne $promNamespace .Release.Namespace) .Values.monitoring.operator) }}
# if operator monitoring is enabled and prometheus namespace is different than operator
# create the above secret in prometheus namespace too.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stash.fullname" . }}-apiserver-cert
  namespace: {{ $promNamespace }}
  labels:
    {{- include "stash.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.tlsCrt }}
  tls.key: {{ $tls.tlsKey }}
---
{{- end }}
# to read the config for terminating authentication
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "stash.fullname" . }}-apiserver-extension-server-authentication-reader
  namespace: kube-system
  labels:
    {{- include "stash.labels" . | nindent 4 }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ template "stash.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
# to delegate authentication and authorization
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "stash.fullname" . }}-apiserver-auth-delegator
  labels:
    {{- include "stash.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ template "stash.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
